//
// Copyright 2023 New Vector Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

import Foundation

struct PhoneNumberCountryDefinition: Hashable, Identifiable {
    let id = UUID()
    let iso2: String
    let name: String
    var prefix: String
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(iso2)
    }
}

let COUNTRIES: [PhoneNumberCountryDefinition] = [
    PhoneNumberCountryDefinition(iso2: "GB", name: "United Kingdom", prefix: "44"),
    PhoneNumberCountryDefinition(iso2: "US", name: "United States", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "AF", name: "Afghanistan", prefix: "93"),
    PhoneNumberCountryDefinition(iso2: "AX", name: "Åland Islands", prefix: "358"),
    PhoneNumberCountryDefinition(iso2: "AL", name: "Albania", prefix: "355"),
    PhoneNumberCountryDefinition(iso2: "DZ", name: "Algeria", prefix: "213"),
    PhoneNumberCountryDefinition(iso2: "AS", name: "American Samoa", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "AD", name: "Andorra", prefix: "376"),
    PhoneNumberCountryDefinition(iso2: "AO", name: "Angola", prefix: "244"),
    PhoneNumberCountryDefinition(iso2: "AI", name: "Anguilla", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "AQ", name: "Antarctica", prefix: "672"),
    PhoneNumberCountryDefinition(iso2: "AG", name: "Antigua & Barbuda", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "AR", name: "Argentina", prefix: "54"),
    PhoneNumberCountryDefinition(iso2: "AM", name: "Armenia", prefix: "374"),
    PhoneNumberCountryDefinition(iso2: "AW", name: "Aruba", prefix: "297"),
    PhoneNumberCountryDefinition(iso2: "AU", name: "Australia", prefix: "61"),
    PhoneNumberCountryDefinition(iso2: "AT", name: "Austria", prefix: "43"),
    PhoneNumberCountryDefinition(iso2: "AZ", name: "Azerbaijan", prefix: "994"),
    PhoneNumberCountryDefinition(iso2: "BS", name: "Bahamas", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "BH", name: "Bahrain", prefix: "973"),
    PhoneNumberCountryDefinition(iso2: "BD", name: "Bangladesh", prefix: "880"),
    PhoneNumberCountryDefinition(iso2: "BB", name: "Barbados", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "BY", name: "Belarus", prefix: "375"),
    PhoneNumberCountryDefinition(iso2: "BE", name: "Belgium", prefix: "32"),
    PhoneNumberCountryDefinition(iso2: "BZ", name: "Belize", prefix: "501"),
    PhoneNumberCountryDefinition(iso2: "BJ", name: "Benin", prefix: "229"),
    PhoneNumberCountryDefinition(iso2: "BM", name: "Bermuda", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "BT", name: "Bhutan", prefix: "975"),
    PhoneNumberCountryDefinition(iso2: "BO", name: "Bolivia", prefix: "591"),
    PhoneNumberCountryDefinition(iso2: "BA", name: "Bosnia", prefix: "387"),
    PhoneNumberCountryDefinition(iso2: "BW", name: "Botswana", prefix: "267"),
    PhoneNumberCountryDefinition(iso2: "BV", name: "Bouvet Island", prefix: "47"),
    PhoneNumberCountryDefinition(iso2: "BR", name: "Brazil", prefix: "55"),
    PhoneNumberCountryDefinition(iso2: "IO", name: "British Indian Ocean Territory", prefix: "246"),
    PhoneNumberCountryDefinition(iso2: "VG", name: "British Virgin Islands", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "BN", name: "Brunei", prefix: "673"),
    PhoneNumberCountryDefinition(iso2: "BG", name: "Bulgaria", prefix: "359"),
    PhoneNumberCountryDefinition(iso2: "BF", name: "Burkina Faso", prefix: "226"),
    PhoneNumberCountryDefinition(iso2: "BI", name: "Burundi", prefix: "257"),
    PhoneNumberCountryDefinition(iso2: "KH", name: "Cambodia", prefix: "855"),
    PhoneNumberCountryDefinition(iso2: "CM", name: "Cameroon", prefix: "237"),
    PhoneNumberCountryDefinition(iso2: "CA", name: "Canada", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "CV", name: "Cape Verde", prefix: "238"),
    PhoneNumberCountryDefinition(iso2: "BQ", name: "Caribbean Netherlands", prefix: "599"),
    PhoneNumberCountryDefinition(iso2: "KY", name: "Cayman Islands", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "CF", name: "Central African Republic", prefix: "236"),
    PhoneNumberCountryDefinition(iso2: "TD", name: "Chad", prefix: "235"),
    PhoneNumberCountryDefinition(iso2: "CL", name: "Chile", prefix: "56"),
    PhoneNumberCountryDefinition(iso2: "CN", name: "China", prefix: "86"),
    PhoneNumberCountryDefinition(iso2: "CX", name: "Christmas Island", prefix: "61"),
    PhoneNumberCountryDefinition(iso2: "CC", name: "Cocos (Keeling) Islands", prefix: "61"),
    PhoneNumberCountryDefinition(iso2: "CO", name: "Colombia", prefix: "57"),
    PhoneNumberCountryDefinition(iso2: "KM", name: "Comoros", prefix: "269"),
    PhoneNumberCountryDefinition(iso2: "CG", name: "Congo - Brazzaville", prefix: "242"),
    PhoneNumberCountryDefinition(iso2: "CD", name: "Congo - Kinshasa", prefix: "243"),
    PhoneNumberCountryDefinition(iso2: "CK", name: "Cook Islands", prefix: "682"),
    PhoneNumberCountryDefinition(iso2: "CR", name: "Costa Rica", prefix: "506"),
    PhoneNumberCountryDefinition(iso2: "HR", name: "Croatia", prefix: "385"),
    PhoneNumberCountryDefinition(iso2: "CU", name: "Cuba", prefix: "53"),
    PhoneNumberCountryDefinition(iso2: "CW", name: "Curaçao", prefix: "599"),
    PhoneNumberCountryDefinition(iso2: "CY", name: "Cyprus", prefix: "357"),
    PhoneNumberCountryDefinition(iso2: "CZ", name: "Czech Republic", prefix: "420"),
    PhoneNumberCountryDefinition(iso2: "CI", name: "Côte d’Ivoire", prefix: "225"),
    PhoneNumberCountryDefinition(iso2: "DK", name: "Denmark", prefix: "45"),
    PhoneNumberCountryDefinition(iso2: "DJ", name: "Djibouti", prefix: "253"),
    PhoneNumberCountryDefinition(iso2: "DM", name: "Dominica", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "DO", name: "Dominican Republic", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "EC", name: "Ecuador", prefix: "593"),
    PhoneNumberCountryDefinition(iso2: "EG", name: "Egypt", prefix: "20"),
    PhoneNumberCountryDefinition(iso2: "SV", name: "El Salvador", prefix: "503"),
    PhoneNumberCountryDefinition(iso2: "GQ", name: "Equatorial Guinea", prefix: "240"),
    PhoneNumberCountryDefinition(iso2: "ER", name: "Eritrea", prefix: "291"),
    PhoneNumberCountryDefinition(iso2: "EE", name: "Estonia", prefix: "372"),
    PhoneNumberCountryDefinition(iso2: "ET", name: "Ethiopia", prefix: "251"),
    PhoneNumberCountryDefinition(iso2: "FK", name: "Falkland Islands", prefix: "500"),
    PhoneNumberCountryDefinition(iso2: "FO", name: "Faroe Islands", prefix: "298"),
    PhoneNumberCountryDefinition(iso2: "FJ", name: "Fiji", prefix: "679"),
    PhoneNumberCountryDefinition(iso2: "FI", name: "Finland", prefix: "358"),
    PhoneNumberCountryDefinition(iso2: "FR", name: "France", prefix: "33"),
    PhoneNumberCountryDefinition(iso2: "GF", name: "French Guiana", prefix: "594"),
    PhoneNumberCountryDefinition(iso2: "PF", name: "French Polynesia", prefix: "689"),
    PhoneNumberCountryDefinition(iso2: "TF", name: "French Southern Territories", prefix: "262"),
    PhoneNumberCountryDefinition(iso2: "GA", name: "Gabon", prefix: "241"),
    PhoneNumberCountryDefinition(iso2: "GM", name: "Gambia", prefix: "220"),
    PhoneNumberCountryDefinition(iso2: "GE", name: "Georgia", prefix: "995"),
    PhoneNumberCountryDefinition(iso2: "DE", name: "Germany", prefix: "49"),
    PhoneNumberCountryDefinition(iso2: "GH", name: "Ghana", prefix: "233"),
    PhoneNumberCountryDefinition(iso2: "GI", name: "Gibraltar", prefix: "350"),
    PhoneNumberCountryDefinition(iso2: "GR", name: "Greece", prefix: "30"),
    PhoneNumberCountryDefinition(iso2: "GL", name: "Greenland", prefix: "299"),
    PhoneNumberCountryDefinition(iso2: "GD", name: "Grenada", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "GP", name: "Guadeloupe", prefix: "590"),
    PhoneNumberCountryDefinition(iso2: "GU", name: "Guam", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "GT", name: "Guatemala", prefix: "502"),
    PhoneNumberCountryDefinition(iso2: "GG", name: "Guernsey", prefix: "44"),
    PhoneNumberCountryDefinition(iso2: "GN", name: "Guinea", prefix: "224"),
    PhoneNumberCountryDefinition(iso2: "GW", name: "Guinea-Bissau", prefix: "245"),
    PhoneNumberCountryDefinition(iso2: "GY", name: "Guyana", prefix: "592"),
    PhoneNumberCountryDefinition(iso2: "HT", name: "Haiti", prefix: "509"),
    PhoneNumberCountryDefinition(iso2: "HM", name: "Heard & McDonald Islands", prefix: "672"),
    PhoneNumberCountryDefinition(iso2: "HN", name: "Honduras", prefix: "504"),
    PhoneNumberCountryDefinition(iso2: "HK", name: "Hong Kong", prefix: "852"),
    PhoneNumberCountryDefinition(iso2: "HU", name: "Hungary", prefix: "36"),
    PhoneNumberCountryDefinition(iso2: "IS", name: "Iceland", prefix: "354"),
    PhoneNumberCountryDefinition(iso2: "IN", name: "India", prefix: "91"),
    PhoneNumberCountryDefinition(iso2: "ID", name: "Indonesia", prefix: "62"),
    PhoneNumberCountryDefinition(iso2: "IR", name: "Iran", prefix: "98"),
    PhoneNumberCountryDefinition(iso2: "IQ", name: "Iraq", prefix: "964"),
    PhoneNumberCountryDefinition(iso2: "IE", name: "Ireland", prefix: "353"),
    PhoneNumberCountryDefinition(iso2: "IM", name: "Isle of Man", prefix: "44"),
    PhoneNumberCountryDefinition(iso2: "IL", name: "Israel", prefix: "972"),
    PhoneNumberCountryDefinition(iso2: "IT", name: "Italy", prefix: "39"),
    PhoneNumberCountryDefinition(iso2: "JM", name: "Jamaica", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "JP", name: "Japan", prefix: "81"),
    PhoneNumberCountryDefinition(iso2: "JE", name: "Jersey", prefix: "44"),
    PhoneNumberCountryDefinition(iso2: "JO", name: "Jordan", prefix: "962"),
    PhoneNumberCountryDefinition(iso2: "KZ", name: "Kazakhstan", prefix: "7"),
    PhoneNumberCountryDefinition(iso2: "KE", name: "Kenya", prefix: "254"),
    PhoneNumberCountryDefinition(iso2: "KI", name: "Kiribati", prefix: "686"),
    PhoneNumberCountryDefinition(iso2: "XK", name: "Kosovo", prefix: "383"),
    PhoneNumberCountryDefinition(iso2: "KW", name: "Kuwait", prefix: "965"),
    PhoneNumberCountryDefinition(iso2: "KG", name: "Kyrgyzstan", prefix: "996"),
    PhoneNumberCountryDefinition(iso2: "LA", name: "Laos", prefix: "856"),
    PhoneNumberCountryDefinition(iso2: "LV", name: "Latvia", prefix: "371"),
    PhoneNumberCountryDefinition(iso2: "LB", name: "Lebanon", prefix: "961"),
    PhoneNumberCountryDefinition(iso2: "LS", name: "Lesotho", prefix: "266"),
    PhoneNumberCountryDefinition(iso2: "LR", name: "Liberia", prefix: "231"),
    PhoneNumberCountryDefinition(iso2: "LY", name: "Libya", prefix: "218"),
    PhoneNumberCountryDefinition(iso2: "LI", name: "Liechtenstein", prefix: "423"),
    PhoneNumberCountryDefinition(iso2: "LT", name: "Lithuania", prefix: "370"),
    PhoneNumberCountryDefinition(iso2: "LU", name: "Luxembourg", prefix: "352"),
    PhoneNumberCountryDefinition(iso2: "MO", name: "Macau", prefix: "853"),
    PhoneNumberCountryDefinition(iso2: "MK", name: "Macedonia", prefix: "389"),
    PhoneNumberCountryDefinition(iso2: "MG", name: "Madagascar", prefix: "261"),
    PhoneNumberCountryDefinition(iso2: "MW", name: "Malawi", prefix: "265"),
    PhoneNumberCountryDefinition(iso2: "MY", name: "Malaysia", prefix: "60"),
    PhoneNumberCountryDefinition(iso2: "MV", name: "Maldives", prefix: "960"),
    PhoneNumberCountryDefinition(iso2: "ML", name: "Mali", prefix: "223"),
    PhoneNumberCountryDefinition(iso2: "MT", name: "Malta", prefix: "356"),
    PhoneNumberCountryDefinition(iso2: "MH", name: "Marshall Islands", prefix: "692"),
    PhoneNumberCountryDefinition(iso2: "MQ", name: "Martinique", prefix: "596"),
    PhoneNumberCountryDefinition(iso2: "MR", name: "Mauritania", prefix: "222"),
    PhoneNumberCountryDefinition(iso2: "MU", name: "Mauritius", prefix: "230"),
    PhoneNumberCountryDefinition(iso2: "YT", name: "Mayotte", prefix: "262"),
    PhoneNumberCountryDefinition(iso2: "MX", name: "Mexico", prefix: "52"),
    PhoneNumberCountryDefinition(iso2: "FM", name: "Micronesia", prefix: "691"),
    PhoneNumberCountryDefinition(iso2: "MD", name: "Moldova", prefix: "373"),
    PhoneNumberCountryDefinition(iso2: "MC", name: "Monaco", prefix: "377"),
    PhoneNumberCountryDefinition(iso2: "MN", name: "Mongolia", prefix: "976"),
    PhoneNumberCountryDefinition(iso2: "ME", name: "Montenegro", prefix: "382"),
    PhoneNumberCountryDefinition(iso2: "MS", name: "Montserrat", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "MA", name: "Morocco", prefix: "212"),
    PhoneNumberCountryDefinition(iso2: "MZ", name: "Mozambique", prefix: "258"),
    PhoneNumberCountryDefinition(iso2: "MM", name: "Myanmar", prefix: "95"),
    PhoneNumberCountryDefinition(iso2: "NA", name: "Namibia", prefix: "264"),
    PhoneNumberCountryDefinition(iso2: "NR", name: "Nauru", prefix: "674"),
    PhoneNumberCountryDefinition(iso2: "NP", name: "Nepal", prefix: "977"),
    PhoneNumberCountryDefinition(iso2: "NL", name: "Netherlands", prefix: "31"),
    PhoneNumberCountryDefinition(iso2: "NC", name: "New Caledonia", prefix: "687"),
    PhoneNumberCountryDefinition(iso2: "NZ", name: "New Zealand", prefix: "64"),
    PhoneNumberCountryDefinition(iso2: "NI", name: "Nicaragua", prefix: "505"),
    PhoneNumberCountryDefinition(iso2: "NE", name: "Niger", prefix: "227"),
    PhoneNumberCountryDefinition(iso2: "NG", name: "Nigeria", prefix: "234"),
    PhoneNumberCountryDefinition(iso2: "NU", name: "Niue", prefix: "683"),
    PhoneNumberCountryDefinition(iso2: "NF", name: "Norfolk Island", prefix: "672"),
    PhoneNumberCountryDefinition(iso2: "KP", name: "North Korea", prefix: "850"),
    PhoneNumberCountryDefinition(iso2: "MP", name: "Northern Mariana Islands", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "NO", name: "Norway", prefix: "47"),
    PhoneNumberCountryDefinition(iso2: "OM", name: "Oman", prefix: "968"),
    PhoneNumberCountryDefinition(iso2: "PK", name: "Pakistan", prefix: "92"),
    PhoneNumberCountryDefinition(iso2: "PW", name: "Palau", prefix: "680"),
    PhoneNumberCountryDefinition(iso2: "PS", name: "Palestine", prefix: "970"),
    PhoneNumberCountryDefinition(iso2: "PA", name: "Panama", prefix: "507"),
    PhoneNumberCountryDefinition(iso2: "PG", name: "Papua New Guinea", prefix: "675"),
    PhoneNumberCountryDefinition(iso2: "PY", name: "Paraguay", prefix: "595"),
    PhoneNumberCountryDefinition(iso2: "PE", name: "Peru", prefix: "51"),
    PhoneNumberCountryDefinition(iso2: "PH", name: "Philippines", prefix: "63"),
    PhoneNumberCountryDefinition(iso2: "PN", name: "Pitcairn Islands", prefix: "870"),
    PhoneNumberCountryDefinition(iso2: "PL", name: "Poland", prefix: "48"),
    PhoneNumberCountryDefinition(iso2: "PT", name: "Portugal", prefix: "351"),
    PhoneNumberCountryDefinition(iso2: "PR", name: "Puerto Rico", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "QA", name: "Qatar", prefix: "974"),
    PhoneNumberCountryDefinition(iso2: "RO", name: "Romania", prefix: "40"),
    PhoneNumberCountryDefinition(iso2: "RU", name: "Russia", prefix: "7"),
    PhoneNumberCountryDefinition(iso2: "RW", name: "Rwanda", prefix: "250"),
    PhoneNumberCountryDefinition(iso2: "RE", name: "Réunion", prefix: "262"),
    PhoneNumberCountryDefinition(iso2: "WS", name: "Samoa", prefix: "685"),
    PhoneNumberCountryDefinition(iso2: "SM", name: "San Marino", prefix: "378"),
    PhoneNumberCountryDefinition(iso2: "SA", name: "Saudi Arabia", prefix: "966"),
    PhoneNumberCountryDefinition(iso2: "SN", name: "Senegal", prefix: "221"),
    PhoneNumberCountryDefinition(iso2: "RS", name: "Serbia", prefix: "381 p"),
    PhoneNumberCountryDefinition(iso2: "SC", name: "Seychelles", prefix: "248"),
    PhoneNumberCountryDefinition(iso2: "SL", name: "Sierra Leone", prefix: "232"),
    PhoneNumberCountryDefinition(iso2: "SG", name: "Singapore", prefix: "65"),
    PhoneNumberCountryDefinition(iso2: "SX", name: "Sint Maarten", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "SK", name: "Slovakia", prefix: "421"),
    PhoneNumberCountryDefinition(iso2: "SI", name: "Slovenia", prefix: "386"),
    PhoneNumberCountryDefinition(iso2: "SB", name: "Solomon Islands", prefix: "677"),
    PhoneNumberCountryDefinition(iso2: "SO", name: "Somalia", prefix: "252"),
    PhoneNumberCountryDefinition(iso2: "ZA", name: "South Africa", prefix: "27"),
    PhoneNumberCountryDefinition(iso2: "GS", name: "South Georgia & South Sandwich Islands", prefix: "500"),
    PhoneNumberCountryDefinition(iso2: "KR", name: "South Korea", prefix: "82"),
    PhoneNumberCountryDefinition(iso2: "SS", name: "South Sudan", prefix: "211"),
    PhoneNumberCountryDefinition(iso2: "ES", name: "Spain", prefix: "34"),
    PhoneNumberCountryDefinition(iso2: "LK", name: "Sri Lanka", prefix: "94"),
    PhoneNumberCountryDefinition(iso2: "BL", name: "St. Barthélemy", prefix: "590"),
    PhoneNumberCountryDefinition(iso2: "SH", name: "St. Helena", prefix: "290 n"),
    PhoneNumberCountryDefinition(iso2: "KN", name: "St. Kitts & Nevis", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "LC", name: "St. Lucia", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "MF", name: "St. Martin", prefix: "590"),
    PhoneNumberCountryDefinition(iso2: "PM", name: "St. Pierre & Miquelon", prefix: "508"),
    PhoneNumberCountryDefinition(iso2: "VC", name: "St. Vincent & Grenadines", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "SD", name: "Sudan", prefix: "249"),
    PhoneNumberCountryDefinition(iso2: "SR", name: "Suriname", prefix: "597"),
    PhoneNumberCountryDefinition(iso2: "SJ", name: "Svalbard & Jan Mayen", prefix: "47"),
    PhoneNumberCountryDefinition(iso2: "SZ", name: "Swaziland", prefix: "268"),
    PhoneNumberCountryDefinition(iso2: "SE", name: "Sweden", prefix: "46"),
    PhoneNumberCountryDefinition(iso2: "CH", name: "Switzerland", prefix: "41"),
    PhoneNumberCountryDefinition(iso2: "SY", name: "Syria", prefix: "963"),
    PhoneNumberCountryDefinition(iso2: "ST", name: "São Tomé & Príncipe", prefix: "239"),
    PhoneNumberCountryDefinition(iso2: "TW", name: "Taiwan", prefix: "886"),
    PhoneNumberCountryDefinition(iso2: "TJ", name: "Tajikistan", prefix: "992"),
    PhoneNumberCountryDefinition(iso2: "TZ", name: "Tanzania", prefix: "255"),
    PhoneNumberCountryDefinition(iso2: "TH", name: "Thailand", prefix: "66"),
    PhoneNumberCountryDefinition(iso2: "TL", name: "Timor-Leste", prefix: "670"),
    PhoneNumberCountryDefinition(iso2: "TG", name: "Togo", prefix: "228"),
    PhoneNumberCountryDefinition(iso2: "TK", name: "Tokelau", prefix: "690"),
    PhoneNumberCountryDefinition(iso2: "TO", name: "Tonga", prefix: "676"),
    PhoneNumberCountryDefinition(iso2: "TT", name: "Trinidad & Tobago", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "TN", name: "Tunisia", prefix: "216"),
    PhoneNumberCountryDefinition(iso2: "TR", name: "Turkey", prefix: "90"),
    PhoneNumberCountryDefinition(iso2: "TM", name: "Turkmenistan", prefix: "993"),
    PhoneNumberCountryDefinition(iso2: "TC", name: "Turks & Caicos Islands", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "TV", name: "Tuvalu", prefix: "688"),
    PhoneNumberCountryDefinition(iso2: "VI", name: "U.S. Virgin Islands", prefix: "1"),
    PhoneNumberCountryDefinition(iso2: "UG", name: "Uganda", prefix: "256"),
    PhoneNumberCountryDefinition(iso2: "UA", name: "Ukraine", prefix: "380"),
    PhoneNumberCountryDefinition(iso2: "AE", name: "United Arab Emirates", prefix: "971"),
    PhoneNumberCountryDefinition(iso2: "UY", name: "Uruguay", prefix: "598"),
    PhoneNumberCountryDefinition(iso2: "UZ", name: "Uzbekistan", prefix: "998"),
    PhoneNumberCountryDefinition(iso2: "VU", name: "Vanuatu", prefix: "678"),
    PhoneNumberCountryDefinition(iso2: "VA", name: "Vatican City", prefix: "39"),
    PhoneNumberCountryDefinition(iso2: "VE", name: "Venezuela", prefix: "58"),
    PhoneNumberCountryDefinition(iso2: "VN", name: "Vietnam", prefix: "84"),
    PhoneNumberCountryDefinition(iso2: "WF", name: "Wallis & Futuna", prefix: "681"),
    PhoneNumberCountryDefinition(iso2: "EH", name: "Western Sahara", prefix: "212"),
    PhoneNumberCountryDefinition(iso2: "YE", name: "Yemen", prefix: "967"),
    PhoneNumberCountryDefinition(iso2: "ZM", name: "Zambia", prefix: "260"),
    PhoneNumberCountryDefinition(iso2: "ZW", name: "Zimbabwe", prefix: "263")
]

let UNICODE_BASE = 127462 - UnicodeScalar("A").value

func getEmojiFlag(countryCode: String) -> String {
    let base: UInt32 = 127397
    var scalar = String.UnicodeScalarView()
    let uppercaseCode = countryCode.uppercased()
    for scalarCode in uppercaseCode.unicodeScalars {
        if let scalarValue = UnicodeScalar(base + scalarCode.value) {
            scalar.append(scalarValue)
        }
    }
    return String(scalar)
}
